// flow-typed signature: 21963cc34e8fafbb614c5c05d4b4e779
// flow-typed version: <<STUB>>/glob-fs_v^0.1.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glob-fs/lib/file' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/filter' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/handler' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/iterators' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/options' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/pattern' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/readers' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/symlinks' {
  declare module.exports: any;
}

declare module 'glob-fs/lib/utils' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/any' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/end' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/exclude' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/include' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/index' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/is' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/isnt' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/npm' {
  declare module.exports: any;
}

declare module 'glob-fs/middleware/unignore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glob-fs/index' {
  declare module.exports: $Exports<'glob-fs'>;
}
declare module 'glob-fs/index.js' {
  declare module.exports: $Exports<'glob-fs'>;
}
declare module 'glob-fs/lib/file.js' {
  declare module.exports: $Exports<'glob-fs/lib/file'>;
}
declare module 'glob-fs/lib/filter.js' {
  declare module.exports: $Exports<'glob-fs/lib/filter'>;
}
declare module 'glob-fs/lib/handler.js' {
  declare module.exports: $Exports<'glob-fs/lib/handler'>;
}
declare module 'glob-fs/lib/iterators.js' {
  declare module.exports: $Exports<'glob-fs/lib/iterators'>;
}
declare module 'glob-fs/lib/options.js' {
  declare module.exports: $Exports<'glob-fs/lib/options'>;
}
declare module 'glob-fs/lib/pattern.js' {
  declare module.exports: $Exports<'glob-fs/lib/pattern'>;
}
declare module 'glob-fs/lib/readers.js' {
  declare module.exports: $Exports<'glob-fs/lib/readers'>;
}
declare module 'glob-fs/lib/symlinks.js' {
  declare module.exports: $Exports<'glob-fs/lib/symlinks'>;
}
declare module 'glob-fs/lib/utils.js' {
  declare module.exports: $Exports<'glob-fs/lib/utils'>;
}
declare module 'glob-fs/middleware/any.js' {
  declare module.exports: $Exports<'glob-fs/middleware/any'>;
}
declare module 'glob-fs/middleware/end.js' {
  declare module.exports: $Exports<'glob-fs/middleware/end'>;
}
declare module 'glob-fs/middleware/exclude.js' {
  declare module.exports: $Exports<'glob-fs/middleware/exclude'>;
}
declare module 'glob-fs/middleware/include.js' {
  declare module.exports: $Exports<'glob-fs/middleware/include'>;
}
declare module 'glob-fs/middleware/index.js' {
  declare module.exports: $Exports<'glob-fs/middleware/index'>;
}
declare module 'glob-fs/middleware/is.js' {
  declare module.exports: $Exports<'glob-fs/middleware/is'>;
}
declare module 'glob-fs/middleware/isnt.js' {
  declare module.exports: $Exports<'glob-fs/middleware/isnt'>;
}
declare module 'glob-fs/middleware/npm.js' {
  declare module.exports: $Exports<'glob-fs/middleware/npm'>;
}
declare module 'glob-fs/middleware/unignore.js' {
  declare module.exports: $Exports<'glob-fs/middleware/unignore'>;
}
