// flow-typed signature: 0ece3182cbb8e0c227b832145e428ecd
// flow-typed version: <<STUB>>/xregexp_v^3.2.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xregexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xregexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xregexp/src/addons/build' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/matchrecursive' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-base' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-blocks' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-categories' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-properties' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-scripts' {
  declare module.exports: any;
}

declare module 'xregexp/src/index' {
  declare module.exports: any;
}

declare module 'xregexp/src/xregexp' {
  declare module.exports: any;
}

declare module 'xregexp/xregexp-all' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xregexp/src/addons/build.js' {
  declare module.exports: $Exports<'xregexp/src/addons/build'>;
}
declare module 'xregexp/src/addons/matchrecursive.js' {
  declare module.exports: $Exports<'xregexp/src/addons/matchrecursive'>;
}
declare module 'xregexp/src/addons/unicode-base.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-base'>;
}
declare module 'xregexp/src/addons/unicode-blocks.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-blocks'>;
}
declare module 'xregexp/src/addons/unicode-categories.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-categories'>;
}
declare module 'xregexp/src/addons/unicode-properties.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-properties'>;
}
declare module 'xregexp/src/addons/unicode-scripts.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-scripts'>;
}
declare module 'xregexp/src/index.js' {
  declare module.exports: $Exports<'xregexp/src/index'>;
}
declare module 'xregexp/src/xregexp.js' {
  declare module.exports: $Exports<'xregexp/src/xregexp'>;
}
declare module 'xregexp/xregexp-all.js' {
  declare module.exports: $Exports<'xregexp/xregexp-all'>;
}
