// flow-typed signature: 1bfae0786e7869140c3cd26c5e331a21
// flow-typed version: <<STUB>>/@emmetio/expand-abbreviation_v^0.5.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emmetio/expand-abbreviation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emmetio/expand-abbreviation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emmetio/expand-abbreviation/dist/expand-full' {
  declare module.exports: any;
}

declare module '@emmetio/expand-abbreviation/dist/expand.cjs' {
  declare module.exports: any;
}

declare module '@emmetio/expand-abbreviation/dist/expand.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emmetio/expand-abbreviation/dist/expand-full.js' {
  declare module.exports: $Exports<'@emmetio/expand-abbreviation/dist/expand-full'>;
}
declare module '@emmetio/expand-abbreviation/dist/expand.cjs.js' {
  declare module.exports: $Exports<'@emmetio/expand-abbreviation/dist/expand.cjs'>;
}
declare module '@emmetio/expand-abbreviation/dist/expand.es.js' {
  declare module.exports: $Exports<'@emmetio/expand-abbreviation/dist/expand.es'>;
}
